### ISSUE TITLE
run on windows

### ISSUE THREAD

**Issue by liangpingding** [allenai/sequential_sentence_classification#6]
I change the code to train.sh to fit in windows.
The code is as below:

set SEED=15270
set PYTORCH_SEED= SEED / 10
set NUMPY_SEED=PYTORCH_SEED / 10
set BERT_VOCAB=https://ai2-s2-research.s3-us-west-2.amazonaws.com/scibert/allennlp_files/scivocab_uncased.vocab
set BERT_WEIGHTS=https://ai2-s2-research.s3-us-west-2.amazonaws.com/scibert/allennlp_files/scibert_scivocab_uncased.tar.gz
set TRAIN_PATH=data\CSAbstruct\train.jsonl
set DEV_PATH=data\CSAbstruct\dev.jsonl
set TEST_PATH=data\CSAbstruct\test.jsonl
set USE_SEP=true  # true for our model. false for baseline
set WITH_CRF=false  # CRF only works for the baseline
set cuda_device=0
set BATCH_SIZE=4
set LR=5e-5
set TRAINING_DATA_INSTANCES=1668
set NUM_EPOCHS=2
set MAX_SENT_PER_EXAMPLE=10
set SENT_MAX_LEN=80
set SCI_SUM=false
set USE_ABSTRACT_SCORES=false
set SCI_SUM_FAKE_SCORES=false  # use fake scores for testing
python -m allennlp.run train sequential_sentence_classification/config.jsonnet --include-package sequential_sentence_classification -s output

But got the error:json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Can you privide me some instruction to run on windows?

**Comment by dakinggg** [comment]
you might have some luck poking around this issue https://github.com/allenai/allennlp/issues/612. Unfortunately I don't have more guidance for you, as none of us develop on Windows.
