### ISSUE TITLE
pip install -r requirements.txt doesn't work

### ISSUE THREAD

**Issue by KacperKubara** [allenai/sequential_sentence_classification#7]
OS: Windows
Python version: 3.7

I created a clean environment with conda. After running the `pip install -r requirements.txt` or `pip3 install -r requirements.txt` I got a following error:

```
λ pip3 install -r requirements.txt
Collecting jsonlines (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4f/9a/ab96291470e305504aa4b7a2e0ec132e930da89eb3ca7a82fbe03167c131/jsonlines-1.2.0-py2.py3-none-any.whl
Obtaining allennlp from git+git://github.com/ibeltagy/allennlp@fp16_and_others#egg=allennlp (from -r requirements.txt (line 2))
  Updating c:\lplp-kacper\code_repo\sequential_sentence_classification\src\allennlp clone (to revision fp16_and_others)
  Running command git fetch -q --tags
  Running command git reset --hard -q ac2b21da6008d0e41d31192ea596153988c000a4
Collecting six (from jsonlines->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting torch>=1.2.0 (from allennlp->-r requirements.txt (line 2))
  ERROR: Could not find a version that satisfies the requirement torch>=1.2.0 (from allennlp->-r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.2.0 (from allennlp->-r requirements.txt (line 2))
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

This I think is related to this issue: https://github.com/pytorch/pytorch/issues/19406
By following the advice there I was able to solve the problem.
The following command solved the error for me before running the `requirements.txt`:
```
conda create -n allennlp python=3.7

pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

pip install allennlp
```

Just posting this here in case if anyone runs in the same problem as I did. I am closing this issue for now since it has been solved.

**Comment by dakinggg** [comment]
Thanks for that!

**Comment by vamsisrinivasmanda** [comment]
pip install -r requirements.txt
Collecting alembic==1.4.2 (from -r requirements.txt (line 1))
Collecting aniso8601==8.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/eb/e4/787e104b58eadc1a710738d4e418d7e599e4e778e52cb8e5d5ef6ddd5833/aniso8601-8.0.0-py2.py3-none-any.whl
Collecting ansible==2.9.5 (from -r requirements.txt (line 3))
Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting astroid==2.3.3 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl
Collecting attrs==19.3.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting backcall==0.1.0 (from -r requirements.txt (line 7))
Collecting bcrypt==3.1.7 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/8b/1d/82826443777dd4a624e38a08957b975e75df859b381ae302cfd7a30783ed/bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl
Collecting blinker==1.4 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz
Collecting cachetools==3.1.1 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
Collecting certifi==2020.4.5.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting cffi==1.14.0 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/f1/c7/72abda280893609e1ddfff90f8064568bd8bcb2c1770a9d5bb5edb2d1fea/cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting chardet==3.0.4 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting click==7.1.2 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
Collecting column==0.4.3 (from -r requirements.txt (line 16))
Collecting cryptography==2.8 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
Collecting decorator==4.4.2 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22))
  Could not find a version that satisfies the requirement distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22)) (from versions: 0.10)
No matching distribution found for distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22))

**Comment by vamsisrinivasmanda** [comment]
> pip install -r requirements.txt
> Collecting alembic==1.4.2 (from -r requirements.txt (line 1))
> Collecting aniso8601==8.0.0 (from -r requirements.txt (line 2))
> Using cached https://files.pythonhosted.org/packages/eb/e4/787e104b58eadc1a710738d4e418d7e599e4e778e52cb8e5d5ef6ddd5833/aniso8601-8.0.0-py2.py3-none-any.whl
> Collecting ansible==2.9.5 (from -r requirements.txt (line 3))
> Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 4))
> Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
> Collecting astroid==2.3.3 (from -r requirements.txt (line 5))
> Using cached https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl
> Collecting attrs==19.3.0 (from -r requirements.txt (line 6))
> Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
> Collecting backcall==0.1.0 (from -r requirements.txt (line 7))
> Collecting bcrypt==3.1.7 (from -r requirements.txt (line 8))
> Using cached https://files.pythonhosted.org/packages/8b/1d/82826443777dd4a624e38a08957b975e75df859b381ae302cfd7a30783ed/bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl
> Collecting blinker==1.4 (from -r requirements.txt (line 9))
> Using cached https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz
> Collecting cachetools==3.1.1 (from -r requirements.txt (line 10))
> Using cached https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
> Collecting certifi==2020.4.5.1 (from -r requirements.txt (line 11))
> Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
> Collecting cffi==1.14.0 (from -r requirements.txt (line 12))
> Using cached https://files.pythonhosted.org/packages/f1/c7/72abda280893609e1ddfff90f8064568bd8bcb2c1770a9d5bb5edb2d1fea/cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
> Collecting chardet==3.0.4 (from -r requirements.txt (line 13))
> Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
> Collecting click==7.1.2 (from -r requirements.txt (line 14))
> Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
> Collecting colorama==0.3.7 (from -r requirements.txt (line 15))
> Using cached https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
> Collecting column==0.4.3 (from -r requirements.txt (line 16))
> Collecting cryptography==2.8 (from -r requirements.txt (line 18))
> Using cached https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
> Collecting decorator==4.4.2 (from -r requirements.txt (line 20))
> Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
> Collecting distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22))
> Could not find a version that satisfies the requirement distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22)) (from versions: 0.10)
> No matching distribution found for distro-info===0.18ubuntu0.18.04.1 (from -r requirements.txt (line 22))

give solution for this im trying from past two days

**Comment by dakinggg** [comment]
These don't look like the required packages for this library. I suspect you are not installing the requirements.txt from this repo.
